[package]
name = "rig"
version = "0.1.0"
authors = ["Keenan Graham <keenangraham@stanford.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
byteordered = "0.4.1"
